version: "3.8"

services:
  db:
    image: postgres:15
    container_name: secret-santa-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: secret-santa-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./config:/config
    environment:
      SPRING_CONFIG_LOCATION: file:/config/
      SPRING_PROFILES_ACTIVE: local,secret

  frontend:
    build:
      context: ./front-end
    container_name: secret-santa-fe
    ports:
      - "5500:80"  # match your original localhost:5500
    restart: unless-stopped

volumes:
  db_data:
