spring:
  application:
    name: secret-santa
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

secret-santa:
  fe:
    base-url: ${FE_BASE_URL}
    gift-form-url: /gift-form.html?id=
  scheduling:
    check-interval: ${CHECK_INTERVAL}
  email-service:
    enabled: ${EMAIL_ENABLED}
  password:
    reset-expiration-minutes: ${RESET_TOKEN_EXP_MIN}


logging:
  level:
    org.springframework.security: ERROR
    cz.oluwagbemiga.santa.be: DEBUG
    org.springframework.http.converter.json: DEBUG
    org.springframework.web: DEBUG
